### ISSUE TITLE
Uncaught TypeError: this.tip(...).find is not a function

### ISSUE THREAD

**Issue by Hoohaha** [vitalets/x-editable#1030]
Follow the quick start, i'd like to try the x-editable with jquery-ui build.
There is no problem in inline mode, but raise an exception when the mode is popup mode.
I find a closed issue https://github.com/vitalets/x-editable/issues/687

What's the problem? How can i resolve it?
  
```
jqueryui-editable.min.js:6 Uncaught TypeError: this.tip(...).find is not a function
    at b.innerShow (jqueryui-editable.min.js:6)
    at b.show (jqueryui-editable.min.js:5)
    at b.show (jqueryui-editable.min.js:5)
    at b.toggle (jqueryui-editable.min.js:5)
    at b.<anonymous> (jqueryui-editable.min.js:5)
    at HTMLAnchorElement.e (jquery-3.2.1.min.js:2)
    at HTMLAnchorElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLAnchorElement.q.handle (jquery-3.2.1.min.js:3)
```

**Comment by Hoohaha** [comment]
X-editable Version:  v1.5.1 
Jquery-UI: v1.12.1 
Jquery: 3.2.1

Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by craiglondon** [comment]
@Hoohaha This plugin isn't working with the latest version of jQuery UI v1.12.1.   I used v1.10.0 and was able to get popups to work.

**Comment by hermik** [comment]
Any solution for this problem - to work on jquery IO 1.12.1?

**Comment by krtschmr** [comment]
thi isn't still updated. fail

**Comment by sandeeppwonderment** [comment]
Is this issue resolved?
