### ISSUE TITLE
[not solved, WIP] x-editable not working with bootstrap 3.0 final

### ISSUE THREAD

**Issue by vpxavier** [vitalets/x-editable#343]
Hello, 
I saw a discussion here (https://github.com/vitalets/x-editable/issues/318) about this but I could not find any solution.

x-editable is not working with bootstrap 3.0; Chrome gives an error:

Uncaught TypeError: Cannot use 'in' operator to search for 'value' in undefined 

This at bootstrap-editable.js:981

Do you have any solution for this?
Thanks a lot,
Xavier

**Comment by bevand10** [comment]
Beware of using the stock CDN version of Bootstrap3 (i.e. the 'Download Bootstrap' version from their [front page](http://getbootstrap.com/getting-started#download) - as it does /not/ contain the tooltip and popover extensions - both required for bootstrap-xeditable to load correctly.
Instead, generate a [customized](http://getbootstrap.com/customize/) version of Bootstrap, ensuring you add these missing dependencies.

**Comment by BoyAbdullah** [comment]
why in my project doesn't work?

VM1815:4 Uncaught TypeError: $(...).datetimepicker is not a function

**Comment by markymar25** [comment]
-->previous thread: guys, it seems you are including bootstrap-editable.js before bootstrap.js file.
It will not work as xeditable js depends on bootstrap.
You should include bootstrap-editable.js after bootstrap.js.
Please re-check and let me know..
@vitalets already tried this one, popup mode on my combodate is still not working

**Comment by mmai** [comment]
@markymar25 Check the jquery includes as well. I was in the same situation and my problem was that there was a second include of  jquery.js after bootstrap.js

**Comment by ankakky88** [comment]
I am still getting some error. I am trying to implement inplaceeditor in an modal.
<img width="943" alt="error" src="https://user-images.githubusercontent.com/6257226/34384736-011b5aee-eb16-11e7-9e1c-a9e14c3d4811.png">

**Comment by MynameAnding** [comment]
hai,Have you solve your problem? i have got 

> I am still getting some error. I am trying to implement inplaceeditor in an modal.
> <img alt="error" width="943" src="https://user-images.githubusercontent.com/6257226/34384736-011b5aee-eb16-11e7-9e1c-a9e14c3d4811.png">
> 
> <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" --   | integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"   | crossorigin="anonymous"></script>
> This is the script that I am using for bootstrap.
have you solve your problem?i met this same problem with you
